// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab5.Models;

namespace lab5.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("lab5.Models.DataAccessModels.OfficeEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("adress");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("OfficeEntity");
                });

            modelBuilder.Entity("lab5.Models.DataAccessModels.WorkerEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name");

                    b.Property<int?>("officeId");

                    b.Property<string>("position");

                    b.Property<string>("surname");

                    b.HasKey("id");

                    b.HasIndex("officeId");

                    b.ToTable("WorkerEntity");
                });

            modelBuilder.Entity("lab5.Models.DataAccessModels.WorkerEntity", b =>
                {
                    b.HasOne("lab5.Models.DataAccessModels.OfficeEntity", "office")
                        .WithMany("workers")
                        .HasForeignKey("officeId");
                });
#pragma warning restore 612, 618
        }
    }
}
